[package]
name = "arcropolis"
version = "2.0.0-beta3"
authors = ["Raytwo <raytwost@gmail.com>, jam1garner <jam1.mcleod@hotmail.com>, blujay <the.blu.dev@gmail.com>, CoolSonicKirby <alihussain2001@gmail.com>"]
edition = "2018"

[package.metadata.skyline]
titleid = "01006A800016E000"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.11"
toml = "0.5.6"
semver = "0.11.0"
lazy_static = "1.4"
owo-colors = "1.0.3"
parking_lot = "0.11.0"
thiserror = "1.0.24"
serde = { version = "1", features = ["derive"] }
rand = { git = "https://github.com/skyline-rs/rand" }
skyline = { git = "https://github.com/ultimate-research/skyline-rs.git" }
skyline-web = { git = "https://github.com/skyline-rs/skyline-web" }
skyline-update = { git = "https://github.com/skyline-rs/skyline-update" }
# Needs to be cloned locally and add link.ld to the root of the directory for the time being. Don't ask why. I don't know.
smash-arc = { path = "../smash-arc", features = [ "smash-runtime", "nozstd" ] }
binread = "2"
ramhorns = "0.9.4"
percent-encoding = "2.1.0"
walkdir = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
