[package]
name = "arcropolis"
version = "3.0.0-beta.3.3"
authors = ["Raytwo <raytwo@arcropolis.com>, blujay <the.blu.dev@gmail.com>, jam1garner <jam@jam1.re>, CoolSonicKirby <alihussain2001@gmail.com>"]
edition = "2018"

[package.metadata.skyline]
titleid = "01006A800016E000"

[lib]
crate-type = ["cdylib"]

[dependencies]
semver = "1"
num-derive = "0.3.3"
num-traits = "0.2"
skyline = { git = "https://github.com/ultimate-research/skyline-rs.git" }
skyline-web = { git = "https://github.com/skyline-rs/skyline-web" }
skyline-config = { git = "https://github.com/skyline-rs/skyline-config" }
strip-ansi-escapes = "0.1.1"
zip = { version = "0.5", default-features = false, features = ["deflate"], optional = true }
gh-updater = { git = "https://github.com/blu-dev/gh-updater", optional = true }
toml = "0.5.8"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0"
serde-xml-rs = "0.3.1"
thiserror = "1.0.30"
lazy_static = "1.4.0"
log = "0.4.14"
parking_lot = "0.11"
bincode = "1.3.3"
orbits = { git = "https://github.com/blu-dev/orbits" }
smash-arc = { git = "https://github.com/jam1garner/smash-arc", features = ["smash-runtime", "rust-zstd"] }
owo-colors = "3.0.1"
skyline-communicate = { git = "https://github.com/blu-dev/skyline-communicate" }
# arcropolis-api = { path = "../arcropolis_api" }
arcropolis-api = { git = "https://github.com/Raytwo/arcropolis_api" }
nn-fuse = { git = "https://github.com/blu-dev/nn-fuse" }
# nn-fuse = { path = "../nn-fuse" }
walkdir = "2.3.2"
prcx = { git = "https://github.com/blu-dev/prcx", branch = "xml-style" }
msbt = { git = "https://github.com/ascclemens/msbt-rs" }
byteordered = "0.4"
# ninput = { git = "https://github.com/blu-dev/ninput" }
# ninput = { path = "../ninput" }
percent-encoding = "2.1.0"

[patch.crates-io]
ring = { git = "https://github.com/skyline-rs/ring", branch = "0.16.20" }
webpki = { git = "https://github.com/skyline-rs/webpki" }

[patch.'https://github.com/ultimate-research/nnsdk-rs']
nnsdk = { git = "https://github.com/blu-dev/nnsdk-rs", branch = "patch-4" }

[patch.'https://github.com/jam1garner/smash-arc']
smash-arc = { git = 'https://github.com/blu-dev/smash-arc' }

# [patch.'https://github.com/blu-dev/orbits']
# orbits = { path = "../orbits" }

[features]
default = ["updater"]
updater = ["zip", "gh-updater"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
