title = "ARCropolis update: Ver. 3.7.0"
date = "09/01/2022"
description = "Thank you for updating to the latest version of ARCropolis.<br/>Please read the following changelog."

[[entries]]
section_title = "Improvement(s)"
contents = """
<ul>
    <li>The region and language for loading regional mods are now derived from your savedata.</li>
</ul>"""

[[entries]]
section_title = "Bug fixe(s)"
contents = """
<ul>
    <li>Fixes to share-to-vanilla in config.json</li>
    <li>Inkling's Roller move no longer crashes the game on extra slots</li>
</ul>"""

[[entries]]
section_title = "Note(s)"
contents = """
<ul>
    <li>ARCropolis is now considered feature complete. Expect mostly bugfixes and QoL improvements from now on.</li>
</ul>"""