title = "ARCropolis update: Ver. 3.8.0"
date = "10/29/2022"
description = "Thank you for updating to the latest version of ARCropolis.<br/>Please read the following changelog."

[[entries]]
section_title = "Improvement(s)"
contents = """
<ul>
    <li>Character UI such as chara_1 files are now lazy loaded to reduce the RAM usage of the game. This essentially means the UI will load immediately when selecting a character instead of when the menu is entered. (by CoolSonicKirby)</li>
</ul>"""

[[entries]]
section_title = "Bug fix(es)"
contents = """
<ul>
    <li>Due to the lazy loading, crashes on the Character Select Screen should be gone</li>
</ul>"""

[[entries]]
section_title = "Note(s)"
contents = """
<ul>
    <li>ARCropolis is now considered feature complete. Expect mostly bugfixes and QoL improvements from now on.</li>
</ul>"""