blank_issues_enabled: true
contact_links:
  - name: Smash Ultimate Modding Hub
    url: https://discord.gg/ASJyTrZ
    about: If you have trouble installing ARCropolis, want to learn or ask questions, ask here
