blank_issues_enabled: true
contact_links:
  - name: A word to users
    url: https://github.com/Raytwo/ARCropolis/discussions
    about: This page is not for you to use. Please head to the Discussions tab instead!
  - name: Smash Ultimate Modding Hub
    url: https://discord.gg/ASJyTrZ
    about: If you have trouble installing ARCropolis, want to learn or ask questions, ask here
  - name: Ultimate Modding Group
    url: https://discord.gg/x9Zss4hkH3
    about: A alternative modding discord for Smash Ultimate
