name: Incorrect behavior
description: Something does not behave the way it should
title: "[Incorrect behavior] Brief description of the issue"
labels: ["bug", "incorrect behavior"]
body:
  - type: input
    id: sys-ver
    attributes:
      label: System Firmware Version
      description: The system version installed on your Nintendo Switch.
      placeholder: ex. 11.0.1
    validations:
      required: true
  - type: input
    id: ams-ver
    attributes:
      label: Atmosphere Version
      description: The version of Atmosphere currently installed on your Nintendo Switch.
      placeholder: ex. 0.18.1
    validations:
      required: true
  - type: input
    id: smash-ver
    attributes:
      label: Smash Version
      description: The version of Smash Ultimate currently installed on your Nintendo Switch (Press + on the icon on the home menu).
      placeholder: ex. 13.0.0
    validations:
      required: true
  - type: input
    id: arc-ver
    attributes:
      label: ARCropolis Version
      description: The version of ARCropolis you are currently running (check the title screen if you can reach it).
      placeholder: ex. 2.1.1
    validations:
      required: true
  - type: dropdown
    id: upd-channel
    attributes:
      label: Version channel
      description: What version channel of ARCropolis are you running?
      options:
        - Stable
        - Beta
    validations:
      required: true
  - type: dropdown
    id: sd-format
    attributes:
      label: SD card formatting
      options:
        - FAT32
        - exFat
    validations:
      required: true
  - type: dropdown
    id: reproducibility
    attributes:
      label: Can this incorrect behavior be consistently reproduced?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: checkboxes
    id: config
    attributes:
      label: Configuration
      description: Check the relevant boxes
      options:
      - label: Legacy discovery
      - label: Modern discovery (>= 3.0.0)
      - label: Irrelevant/Not provided
  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: Explain what SHOULD have happened but didn't, and detailed steps to observe it.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: If the incorrect behavior can be shown, please provide a screenshot if possible.
  - type: input
    id: modpack
    attributes:
      label: Minimal modpack to reproduce the panic
      description: If a specific set of mods is necessary to observe the issue, please provide it
