name: Panic
description: Plugin has panicked
title: "[Panic] Brief description of the issue"
labels: ["bug", "panic"]
body:
  - type: input
    id: sys-ver
    attributes:
      label: System Firmware Version
      description: The system version installed on your Nintendo Switch.
      placeholder: ex. 11.0.1
    validations:
      required: true
  - type: input
    id: ams-ver
    attributes:
      label: Atmosphere Version
      description: The version of Atmosphere currently installed on your Nintendo Switch.
      placeholder: ex. 0.18.1
    validations:
      required: true
  - type: input
    id: smash-ver
    attributes:
      label: Smash Version
      description: The version of Smash Ultimate currently installed on your Nintendo Switch (Press + on the icon on the home menu).
      placeholder: ex. 13.0.0
    validations:
      required: true
  - type: input
    id: arc-ver
    attributes:
      label: ARCropolis Version
      description: The version of ARCropolis you are currently running (check the title screen if you can reach it).
      placeholder: ex. 2.1.1
    validations:
      required: true
  - type: dropdown
    id: upd-channel
    attributes:
      label: Version channel
      description: What version channel of ARCropolis are you running?
      options:
        - Stable
        - Beta
    validations:
      required: true
  - type: dropdown
    id: sd-format
    attributes:
      label: SD card formatting
      options:
        - FAT32
        - exFat
    validations:
      required: true
  - type: checkboxes
    id: config
    attributes:
      label: Configuration
      description: Check the relevant boxes
      options:
      - label: Legacy discovery
      - label: Modern discovery (>= 3.0.0)
      - label: Irrelevant/Not provided
  - type: textarea
    id: reproducing
    attributes:
      label: Steps to reproduce
      description: Give the surrounding context and detailed informations on how to reproduce the panic.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: If a panic window with a code ending in ``69`` shows up, please select "Details" and provide a screenshot of the message. If you cannot provide a screenshot, write down the message in its entirety.
    validations:
      required: true
  - type: input
    id: modpack
    attributes:
      label: Minimal modpack to reproduce the panic
      description: If a specific set of mods is necessary to reproduce the panic, please provide it
