name: Quality of Life
description: Changes to make ARCropolis better or simpler
title: "[Qualify of Life] Brief description of the change"
labels: ["enhancement"]
body:
  - type: textarea
    id: improvement
    attributes:
      label: Explain the improvement(s).
      description: Give a clear and short description of the change
      placeholder: Performing this specific action could be more straightforward.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Provide extra details
      description: Describe how the change should be implemented, or even provide a [Mermaid diagram](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) if needed.
