# No idea if this will work
name: Build a branch
on: [workflow_dispatch]
jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
    - name: Build ARCropolis and package it
      uses: dtolnay/install@master
      with:
        crate: cargo-skyline
    - run: cargo skyline package --no-skyline
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: ARCropolis
        path: target/release.zip
